FROM node:20-alpine
WORKDIR /app
RUN npm install -g pnpm
COPY pnpm-lock.yaml ./
COPY services/alert-engine/package.json ./
RUN pnpm install --prod --no-frozen-lockfile
COPY services/alert-engine ./
CMD ["node", "index.js"]
